framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true
    validation: {enable_annotations: true}

    #esi: true
    #fragments: true
    php_errors:
        log: true
